name: Send string contents to Datadog

on:
  workflow_call:
    inputs:
      string_value:
        type: string
      datadog_service:
        type: string
        default: github-actions
      base64_encoded:
        type: boolean
        default: false
    secrets:
      datadog_api_key:
        required: true

jobs:
  send_to_datadog:
    name: Send
    runs-on: ubuntu-latest
    steps:
      - name: Send to Datadog
        run: |
          string_value='${{ inputs.string_value }}'
          if [[ '${{ inputs.base64_encoded }}' == 'true' ]];
          then
            string_value=$(echo $string_value | base64 --decode)
          fi

          echo $string_value > datadog_post

          curl -X POST "https://http-intake.logs.datadoghq.com/api/v2/logs?service=${{ inputs.datadog_service }}" \
          -H "Content-Type: text/plain" \
          -H "DD-API-KEY: ${{ secrets.datadog_api_key }}" \
          -d @datadog_post
