name: Send string contents to Datadog

on:
  workflow_call:
    inputs:
      string_value:
        type: string
      datadog_service:
        type: string
        default: github-actions
    secrets:
      datadog_api_key:
        required: true

jobs:
  send_to_datadog:
    name: Send
    runs-on: ubuntu-latest
    steps:
      - name: Send to Datadog
        run: |
          curl -X POST "https://http-intake.logs.datadoghq.com/api/v2/logs?service=${{ inputs.datadog_service }}" \
          -H "Content-Type: text/plain" \
          -H "DD-API-KEY: ${{ secrets.datadog_api_key }}" \
          -d ${{ inputs.string_value }}
