on:
  workflow_call:

name: Output Contexts
jobs:
  contexts:
    runs-on: ubuntu-latest
    name: Output Contexts
    steps:
      - name: 'github.*'
        continue-on-error: true
        run: echo -ne "${{ toJSON(github) }}"
      - name: 'env.*'
        continue-on-error: true
        run: echo -ne "${{ toJSON(env) }}"
      - name: 'job.*'
        continue-on-error: true
        run: echo -ne "${{ toJSON(job) }}"
      - name: 'steps.*'
        continue-on-error: true
        run: echo -ne "${{ toJSON(steps) }}"
      - name: 'runner.*'
        continue-on-error: true
        run: echo -ne "${{ toJSON(runner) }}"
      - name: 'secrets.*'
        continue-on-error: true
        run: echo -ne "${{ toJSON(secrets) }}"
      - name: 'matrix.*'
        continue-on-error: true
        run: echo -ne "${{ toJSON(matrix) }}"
      - name: 'needs.*'
        continue-on-error: true
        run: echo -ne "${{ toJSON(needs) }}"
      - name: 'inputs.*'
        continue-on-error: true
        run: echo -ne "${{ toJSON(inputs) }}"
