name: Send string contents to stdout

on:
  workflow_call:
    inputs:
      string_value:
        type: string
      base64_encoded:
        type: boolean
        default: false

jobs:
  send_to_stdout:
    name: Send
    runs-on: ubuntu-latest
    steps:
      - name: Send to stdout
        run: |
          string_value=$(cat <<'EOF'
          ${{ inputs.string_value }}
          EOF
          )

          if [[ '${{ inputs.base64_encoded }}' == 'true' ]];
          then
            string_value=$(echo $string_value | base64 --decode)
          fi

          echo "$string_value"
